### ISSUE TITLE
No colors on plugin output

### ISSUE THREAD

**Issue by seboudry** [TamCore/autoupdate-oh-my-zsh-plugins#20]
While reading plugin code I noticed that it supports some coloring.
But this doesn't work for me. The `-t 1` test returns `false`. Don't know why...
https://github.com/TamCore/autoupdate-oh-my-zsh-plugins/blob/708bd95debaf6b12ead3af0cfd41f1a1d872556c/autoupdate.plugin.zsh#L8

```
$ lsb_release -d
Description:	Ubuntu 20.04.1 LTS
$ zsh --version
zsh 5.8 (x86_64-ubuntu-linux-gnu)
```

**Comment by TamCore** [comment]
What output do you get from `tty`?

Maybe we could also change the `[ -t 1]` to `[[ $- == *i* ]]`

**Comment by seboudry** [comment]
Hi!
Here's my outputs:
```
$ tty
/dev/pts/0
$ echo $-
569JNRXZghikms
```

Indeed, that's not the fd `1` that is used but `0`.

**Comment by TamCore** [comment]
You're connected via SSH, right?

`-t 1` only checks if fd1 (or stdout) is connected to a terminal, rather than being piped to a file or something. In your case, `/proc/self/fd/1` (stdout (`/dev/stdout`)) is most likely pointing to `/dev/pts/0`. Which is fine. 

Do you get colored output, when executing `.oh-my-zsh/tools/upgrade.sh` ?

**Comment by seboudry** [comment]
mmmmh not using SSH, maybe it's powerlevel10k that do the fd redirect...
Yes, I have coloured output on omz upgrade.
